[general]
import = ["rose-pine.toml"]

[colors.cursor]
# The color of the cursor itself
cursor = "#FF5555"
# The color of the character *under* the cursor
text = "#181818"

[cursor]
style = { shape = "Block", blinking = "Always" }
# How fast it blinks (in milliseconds)
blink_interval = 500
thickness = 0.3
unfocused_hollow = true

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"
