[general]
import = ["rose-pine.toml"]

[colors.cursor]
cursor = "#FF5555"
text = "#181818"

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_interval = 500
thickness = 0.3
unfocused_hollow = true

[font]
size = 14.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Medium"
